version: '3.0'

x-restart-policy: &restart_policy
  restart: unless-stopped

x-network-policy: &network_policy
  networks:
    - grafana_network

services:
  postgres:
    image: postgres:15
    <<: [*restart_policy, *network_policy]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:11.2.0
    <<: [*restart_policy, *network_policy]
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - postgres

networks:
  grafana_network:
    driver: bridge
